package main

import (
	"fmt"
	"log"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/tapas/go-user-service/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/tapas/go-user-service/internal/user/model"
)

// @title User Service API
// @version 1.0
// @description This is a sample user service server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
func main() {
	app, err := InitializeApp()
	if err != nil {
		log.Fatalf("Failed to initialize app: %v", err)
	}

	// Auto-migrate the User model
	err = app.DB.AutoMigrate(&model.User{})
	if err != nil {
		log.Fatalf("Failed to auto-migrate database: %v", err)
	}

	// Swagger UI
	app.Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	port := app.Config.App.Port
	log.Printf("Starting server on :%d", port)
	app.Router.Run(fmt.Sprintf(":%d", port))
}
