// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/go-redis/redis/v8"
	"github.com/yi-tech/go-user-service/internal/config"
	"github.com/yi-tech/go-user-service/internal/domain/auth"
	"github.com/yi-tech/go-user-service/internal/middleware"
	"github.com/yi-tech/go-user-service/internal/provider"
	auth2 "github.com/yi-tech/go-user-service/internal/repository/auth"
	user2 "github.com/yi-tech/go-user-service/internal/repository/user"
	auth3 "github.com/yi-tech/go-user-service/internal/service/auth"
	"github.com/yi-tech/go-user-service/internal/service/user"
	"github.com/yi-tech/go-user-service/internal/transport/grpc"
	auth5 "github.com/yi-tech/go-user-service/internal/transport/grpc/auth"
	user4 "github.com/yi-tech/go-user-service/internal/transport/grpc/user"
	"github.com/yi-tech/go-user-service/internal/transport/http"
	auth4 "github.com/yi-tech/go-user-service/internal/transport/http/auth"
	user3 "github.com/yi-tech/go-user-service/internal/transport/http/user"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp creates the application dependencies.
func InitializeApp() (*App, error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := provider.ProvideDatabase(config)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository)
	logger, err := provider.ProvideLogger(config)
	if err != nil {
		return nil, err
	}
	handler := ProvideUserHttpHandler(userService, logger)
	client, err := provider.ProvideRedisClient(config)
	if err != nil {
		return nil, err
	}
	authRepository := ProvideAuthRepository(client)
	authService := ProvideAuthService(userService, authRepository, config)
	authHandler := ProvideAuthHttpHandler(authService, logger)
	engine := ProvideRouter(handler, authHandler, authService, logger)
	server := ProvideHTTPServer(engine, config)
	grpcConfig := ProvideGRPCConfig(config)
	grpcServer := ProvideGRPCServer(userService, authService, logger, grpcConfig)
	app := &App{
		HTTPServer: server,
		GRPCServer: grpcServer,
		DB:         db,
		Config:     config,
		Logger:     logger,
	}
	return app, nil
}

// wire.go:

// ProvideGRPCConfig provides the gRPC server configuration
func ProvideGRPCConfig(cfg *config.Config) *grpc.Config {
	return &grpc.Config{
		GRPCPort: cfg.GRPC.Port,
		HTTPPort: cfg.GRPC.Port + 1,
	}
}

// ProvideGRPCServer creates a new gRPC server
func ProvideGRPCServer(userService user.UserService, authService auth.AuthService, logger *zap.Logger, cfg *grpc.Config) *grpc.Server {
	return grpc.NewServer(userService, authService, logger, cfg)
}

// App represents the main application structure.
type App struct {
	HTTPServer *http.Server // HTTP server (Gin) instance
	GRPCServer *grpc.Server // gRPC server instance
	DB         *gorm.DB
	Config     *config.Config
	Logger     *zap.Logger
}

// Provider functions for repositories
func ProvideUserRepository(db *gorm.DB) user2.UserRepository {
	return user2.NewUserRepository(db)
}

func ProvideAuthRepository(redis2 *redis.Client) auth2.AuthRepository {
	return auth2.NewAuthRepository(redis2)
}

// Provider functions for services
func ProvideUserService(repo user2.UserRepository) user.UserService {
	return user.NewUserService(repo)
}

func ProvideAuthService(userService user.UserService, authRepo auth2.AuthRepository, cfg *config.Config) auth.AuthService {
	return auth3.NewService(userService, authRepo, cfg)
}

// Provider functions for HTTP handlers
func ProvideUserHttpHandler(userService user.UserService, logger *zap.Logger) *user3.Handler {
	return user3.NewHandler(userService, logger)
}

func ProvideAuthHttpHandler(authService auth.AuthService, logger *zap.Logger) *auth4.Handler {
	return auth4.NewHandler(authService, logger)
}

// Provider functions for gRPC handlers
func ProvideUserGrpcHandler(userService user.UserService, logger *zap.Logger) *user4.Handler {
	return user4.NewHandler(userService, logger)
}

func ProvideAuthGrpcHandler(authService auth.AuthService, logger *zap.Logger) *auth5.Handler {
	return auth5.NewHandler(authService, logger)
}

// Provider function for middleware
func ProvideAuthMiddleware(authService auth.AuthService, logger *zap.Logger) gin.HandlerFunc {
	return middleware.AuthMiddleware(authService, logger)
}

// Provider function for router
func ProvideRouter(userHandler *user3.Handler, authHandler *auth4.Handler, authService auth.AuthService, logger *zap.Logger) *gin.Engine {
	return http.NewRouter(userHandler, authHandler, authService, logger)
}

// ProvideHTTPServer creates a new HTTP server
func ProvideHTTPServer(router *gin.Engine, cfg *config.Config) *http.Server {
	return http.NewServer(router, cfg)
}
