app:
  name: "User Auth Service (local)"
  env: "local"
  port: 8080

database:
  driver: "postgres"
  source: "host=host.docker.internal port=5432 user=ewu password=123456 dbname=user_auth_dev sslmode=disable"

redis:
  addr: "host.docker.internal:6379"
  password: ""
  db: 0

jwt:
  secret: "local_secret_key"
  access_token_expire_minutes: 15
  refresh_token_expire_days: 7